# Generated by Django 3.2.10 on 2022-04-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('file', models.CharField(blank=True, choices=[], max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('file', models.CharField(blank=True, choices=[('pw_performance.py', 'pw_performance.py'), ('simple_example.py', 'simple_example.py'), ('test.py', 'test.py')], max_length=250, null=True)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('dashboards', models.ManyToManyField(blank=True, null=True, to='viz.Dashboard', verbose_name='Dashboards with Access')),
            ],
        ),
    ]
