# Generated by Django 4.0.4 on 2022-05-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='file',
            field=models.CharField(blank=True, choices=[('map_sample.py', 'map_sample.py'), ('bubble_sample.py', 'bubble_sample.py')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='file',
            field=models.CharField(blank=True, choices=[('test_styling.py', 'test_styling.py'), ('simple_example.py', 'simple_example.py'), ('test.py', 'test.py')], max_length=250, null=True),
        ),
    ]
