# Generated by Django 4.0.4 on 2022-06-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0002_alter_chart_file_alter_dashboard_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='file',
            field=models.CharField(blank=True, choices=[('test_styling.py', 'test_styling.py'), ('simple_example.py', 'simple_example.py'), ('test.py', 'test.py'), ('test2.py', 'test2.py')], max_length=250, null=True),
        ),
    ]
